DROP TABLE IF EXISTS TBL_PRODUCTS;
 
CREATE TABLE TBL_PRODUCTS(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  quantity VARCHAR(250) NOT NULL,
  price VARCHAR(250) DEFAULT NULL
);